version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"  # Gunicorn
    volumes:
      - .:/app
    command: >
      sh -c "gunicorn --access-logfile - --error-logfile - -w 1 -k eventlet -b 0.0.0.0:5000 --timeout 120 app:app &
            python app_files.py"
    depends_on:
      - worker
      - flower

  worker:
    build: .
    volumes:
      - .:/app
    command: >
      celery -A app:celery worker --concurrency=20 --loglevel=INFO --pool=solo
    depends_on:
      - redis

  flower:
    build: .
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    command: >
      celery -A app:celery flower --port=5555
    depends_on:
      - redis

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
