version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"  # Gunicorn
    volumes:
      - .:/app
    command: >
      sh -c "gunicorn --access-logfile - --error-logfile - -w 1 -k eventlet -b 0.0.0.0:5000 --timeout 120 app:app &&
            python app_files.py"

  worker:
    build: .
    volumes:
      - .:/app
    command: >
      celery -A app:celery worker --loglevel=INFO --pool=solo

  flower:
    build: .
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    command: >
      celery -A app:celery flower --port=5555