version: '3.8'

services:
  gunicorn:
    build: .
    ports:
      - "5000:5000"  # Gunicorn
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: >
      sh -c ". /venv/bin/activate && gunicorn --access-logfile - --error-logfile - -w 1 -k eventlet -b 0.0.0.0:5000 --timeout 120 app:app &&
            python app_files.py"
    restart: unless-stopped
    mem_limit: 1g  # Ограничение памяти

  worker:
    build: .
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: >
      sh -c ". /venv/bin/activate && celery -A app:celery worker --loglevel=INFO --pool=solo"
    restart: unless-stopped
    mem_limit: 1g  # Ограничение памяти

  flower:
    build: .
    ports:
      - "5555:5555"
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: >
      sh -c ". /venv/bin/activate && celery -A app:celery flower --port=5555"
    restart: unless-stopped
    mem_limit: 1g  # Ограничение памяти